### ISSUE TITLE
Allow EI flights to be booked via BA

### ISSUE THREAD

**Issue by reedy** [adamhwang/ita-matrix-powertools#10]
BA's website can price/sell some EI flights (on EI codes). It'd be useful if the magic linking which allows you to book BA codes on BA or IB, would allow EI codes to be booked (or at least, try to) on BA.com

**Comment by reedy** [comment]
```
function printBA() {
  if (!anyCarriers("IB", "BA")) {
    return;
  }
```

Is it as simple as adding `"EI"` into that list?

**Comment by adamhwang** [comment]
Yes! PRs welcome

**Comment by reedy** [comment]
Sweet. I'll create one later.

Late night flight booking; frustration that the add-on wouldn't show me a BA link for EI flights. File a task. Go back to looking at flights. Think this can't be that hard...

😁

**Comment by adamhwang** [comment]
There's also an option to show all flights for airlines. That might be easier in the meantime.

**Comment by reedy** [comment]
> There's also an option to show all flights for airlines. That might be easier in the meantime.

Where's that OOI?
